app <- ShinyDriver$new("../../")
app$snapshotInit("ASGA_test")

app$setInputs(Wiki = "click")
app$setInputs(innavbar = "About")
app$setInputs(innavbar = "Wiki")
app$setInputs(innavbar = "Home")
app$setInputs(GetStarted = "click")
app$setInputs(Test_unit = "click")
app$setInputs(`Home-KMT_Minus_End_Seeds` = TRUE)
app$setInputs(`Home-k_core_area` = TRUE)
app$setInputs(`Home-Fiber_Curv_Length` = TRUE)
app$setInputs(`Home-Fiber_Area` = TRUE)
app$setInputs(`Home-KMT_Torque` = TRUE)
app$setInputs(`Home-End_Morphology` = TRUE)
app$setInputs(`Home-Curvature` = TRUE)
app$setInputs(`Home-IKD` = TRUE)
app$setInputs(`Home-KMT_number` = TRUE)
app$setInputs(`Home-All_Anaysis` = TRUE)
app$setInputs(Submit = "click")
app$setInputs(`innavbar-GS` = "Report")
app$snapshot()
